import {paths,mutations} from './data.js';
import {KEY,validate,summary,record} from './model.js';
const $=s=>document.querySelector(s);
let state={version:1,logs:[]},limit=50,timer,storageReady=true;
function toast(text){$('#toast').textContent=text;clearTimeout(timer);timer=setTimeout(()=>$('#toast').textContent='',5500);}
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}catch{storageReady=false;toast('保存データを読み込めません。既存データ保護のため記録を停止しました。バックアップの読み込みをお試しください。');}
function commit(next,restore=false){if(!storageReady&&!restore){toast('既存データを保護しています。バックアップを読み込んでください。');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));state=next;storageReady=true;render();return true;}catch{toast('保存できませんでした。ブラウザの保存設定や空き容量をご確認ください。');return false;}}
function add(id){const before=summary(state);if(!commit(record(state,id)))return;const after=summary(state);const skills=after.unlocked.filter(s=>!before.unlocked.some(b=>b.id===s.id));const badges=after.mutations.filter(m=>!before.mutations.includes(m));toast(['＋20 XP！ 本日のこだわり、受理しました。',after.level>before.level?`LEVEL UP! Lv.${after.level}`:'',...skills.map(s=>`✦ スキル解放：${s.name}`),...badges.map(m=>`🧬 突然変異：${m.name}`)].filter(Boolean).join('\n'));}
function render(){const s=summary(state);$('#level').textContent=s.level;$('#xp').textContent=`${s.xp} XP`;$('#level-progress').value=s.progress;$('#next-level').textContent=`次のレベルまで ${100-s.progress} XP`;
 $('#unlocked').textContent=s.unlocked.length;$('#actions').textContent=state.logs.length;$('#rank').textContent=s.level>=20?'こだわりを極めし仙人':s.level>=10?'沼に住民票を移した人':s.level>=5?'違いが気になり始めた人':s.level>=2?'趣味のある一般人':'可能性しかない一般人';
 $('#paths').innerHTML=paths.map(p=>{const count=s.counts[p.id],next=p.skills.find(k=>k.count>count);return `<article class="path"><div class="path-head"><span class="path-icon">${p.icon}</span><div><h3>${p.name}</h3><p>${p.tagline}</p></div><button data-add="${p.id}" aria-label="${p.action}を記録">＋ 記録</button></div><div class="nodes">${p.skills.map((k,i)=>`<button class="node ${count>=k.count?'done':k===next?'next':''}" data-skill="${k.id}" aria-label="${k.name}、${count>=k.count?'解放済み':`解放まであと${k.count-count}回`}"><span class="node-icon">${count>=k.count?(i===3?'🧙':p.icon):k===next?'◇':'🔒'}</span><span class="node-name">${k.name}</span><small>${count>=k.count?'✓ 解放済み':`${Math.min(count,k.count)} / ${k.count} 回`}</small></button>`).join('')}</div></article>`;}).join('');
 $('#mutation-list').innerHTML=mutations.map(m=>`<article class="mutation ${s.mutations.includes(m)?'done':''}"><span>${m.icon}</span><h3>${m.name}</h3><p>${m.text}</p><b>${s.mutations.includes(m)?'✦ 解放済み':'未解放'}</b></article>`).join('');
 $('#logs').replaceChildren();for(const l of [...state.logs].reverse().slice(0,limit)){const p=paths.find(p=>p.id===l.path),row=document.createElement('div');row.className='log';const icon=document.createElement('span');icon.textContent=p.icon;const text=document.createElement('div');text.textContent=p.action;const date=document.createElement('small');date.textContent=new Date(l.date).toLocaleString('ja-JP')+' · ＋20 XP';text.append(date);const btn=document.createElement('button');btn.textContent='取り消す';btn.addEventListener('click',()=>{if(confirm('この記録を取り消しますか？経験値と解放スキルも戻ります。'))commit({...state,logs:state.logs.filter(x=>x.id!==l.id)});});row.append(icon,text,btn);$('#logs').append(row);}if(!state.logs.length)$('#logs').textContent='まだ白紙です。最初の寄り道を記録しましょう。';$('#more').hidden=state.logs.length<=limit;
}
$('#paths').addEventListener('click',e=>{const addBtn=e.target.closest('[data-add]');if(addBtn){add(addBtn.dataset.add);return;}const btn=e.target.closest('[data-skill]');if(!btn)return;const p=paths.find(p=>p.skills.some(k=>k.id===btn.dataset.skill)),k=p.skills.find(k=>k.id===btn.dataset.skill),count=summary(state).counts[p.id];$('#detail-content').innerHTML=`<div class="detail-icon">${p.icon}</div><p class="eyebrow">${p.name} / STAGE ${p.skills.indexOf(k)+1}</p><h2>${k.name}</h2><p class="quote">${k.joke}</p><p>${p.action}：累計 ${k.count} 回で解放</p><p>${count>=k.count?'✦ 解放済み！':`現在 ${count} 回。あと ${k.count-count} 回で進化。`}</p><p class="fine">分野内の累計回数で順番に解放されます。道具の購入は不要です。</p>`;$('#detail').showModal();});
$('#choices').innerHTML=paths.map(p=>`<button data-choice="${p.id}">${p.icon} ${p.action}</button>`).join('');$('#choices').addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(b){$('#picker').close();add(b.dataset.choice);}});$('#start').onclick=()=>$('#picker').showModal();document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>{const active=t===b;t.setAttribute('aria-selected',active);$('#'+t.dataset.tab).hidden=!active;});});
$('#more').onclick=()=>{limit+=50;render();};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`oji-skill-tree-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20000000)throw Error('ファイルが大きすぎます');const next=validate(JSON.parse(await file.text()));if(confirm(`${next.logs.length}件の記録を読み込み、現在の記録を置き換えますか？`)){if(commit(next,true))toast('バックアップを復元しました。');}}catch{toast('読み込めませんでした。正しいバックアップJSONをご指定ください。');}finally{e.target.value='';}};
window.addEventListener('storage',e=>{if(e.key===KEY){try{state=e.newValue?validate(JSON.parse(e.newValue)):{version:1,logs:[]};storageReady=true;render();}catch{storageReady=false;toast('別タブの保存データが不正です。記録を停止しました。');}}});render();
